#let config = (
  en: (
    lang: "en",
    appendix: (supplement: "Appendix", numbering: "A.1"),
    sans_font: ("Lexend", "Noto Sans CJK JP"),
    serif_font: ("Libertinus Serif", "Noto Serif CJK JP"),
    math_font: "Libertinus Math",
    mono_font: "IBM Plex Mono",
    draft: "draft",
    date_format: "[month repr:long] [year]",
    proof: [_Proof._],
  ),
  zh: (
    lang: "zh",
    region: "CN",
    figure: "圖",
    table: "表",
    chapter: "篇",
    section: "節",
    toc: "目錄",
    appendix: (
      supplement: "附錄",
      numbering: (a, ..) => {
        ("甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸").at(a - 1)
      },
    ),
    title_font: ((name: "Lexend", covers: "latin-in-cjk"), "尙古黑體SC"),
    sans_font: ((name: "Lexend", covers: "latin-in-cjk"), "尙古黑體SC"),
    serif_font: ((name: "New Computer Modern", covers: "latin-in-cjk"), "尙古明體SC"),
    math_font: ("New Computer Modern Math", "尙古明體SC"),
    mono_font: "IBM Plex Mono",
    italic_font: ((name: "New Computer Modern", covers: "latin-in-cjk"), "Zhuque Fangsong (technical preview)"),
    draft: "稿",
    date_format: "[year] 年 [month repr:numerical] 月",
    proof: [_證明_],
  ),
  ja: (
    lang: "ja",
    appendix: (supplement: "付録", numbering: "A.1"),
    sans_font: ((name: "Lexend", covers: "latin-in-cjk"), "Noto Sans CJK JP"),
    serif_font: ((name: "Libertinus Serif", covers: "latin-in-cjk"), "Noto Serif CJK JP"),
    math_font: "Libertinus Math",
    mono_font: "IBM Plex Mono",
    draft: "下書き",
    date_format: "[year] 年 [month repr:numerical] 月",
  ),
)
